/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ClusterManagementAPI_constants.h"

namespace ClusterAdmin { namespace Thrift {

const ClusterManagementAPIConstants g_ClusterManagementAPI_constants;

ClusterManagementAPIConstants::ClusterManagementAPIConstants() {
}

}} // namespace

