DROP TABLE IF EXISTS `pw_stat`.`tbl_user_hero_talentset`;
CREATE TABLE  `pw_stat`.`tbl_user_hero_talentset` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hero_id` bigint(20) unsigned NOT NULL COMMENT 'id from tbl_user_hero_stats_2',
  `auid` bigint(20) unsigned NOT NULL COMMENT 'aggregator uid',
  `timestamp` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'unixtime',
  `talent1` varchar(20) NOT NULL DEFAULT '0',
  `talent2` varchar(20) NOT NULL DEFAULT '0',
  `talent3` varchar(20) NOT NULL DEFAULT '0',
  `talent4` varchar(20) NOT NULL DEFAULT '0',
  `talent5` varchar(20) NOT NULL DEFAULT '0',
  `talent6` varchar(20) NOT NULL DEFAULT '0',
  `talent7` varchar(20) NOT NULL DEFAULT '0',
  `talent8` varchar(20) NOT NULL DEFAULT '0',
  `talent9` varchar(20) NOT NULL DEFAULT '0',
  `talent10` varchar(20) NOT NULL DEFAULT '0',
  `talent11` varchar(20) NOT NULL DEFAULT '0',
  `talent12` varchar(20) NOT NULL DEFAULT '0',
  `talent13` varchar(20) NOT NULL DEFAULT '0',
  `talent14` varchar(20) NOT NULL DEFAULT '0',
  `talent15` varchar(20) NOT NULL DEFAULT '0',
  `talent16` varchar(20) NOT NULL DEFAULT '0',
  `talent17` varchar(20) NOT NULL DEFAULT '0',
  `talent18` varchar(20) NOT NULL DEFAULT '0',
  `talent19` varchar(20) NOT NULL DEFAULT '0',
  `talent20` varchar(20) NOT NULL DEFAULT '0',
  `talent21` varchar(20) NOT NULL DEFAULT '0',
  `talent22` varchar(20) NOT NULL DEFAULT '0',
  `talent23` varchar(20) NOT NULL DEFAULT '0',
  `talent24` varchar(20) NOT NULL DEFAULT '0',
  `talent25` varchar(20) NOT NULL DEFAULT '0',
  `talent26` varchar(20) NOT NULL DEFAULT '0',
  `talent27` varchar(20) NOT NULL DEFAULT '0',
  `talent28` varchar(20) NOT NULL DEFAULT '0',
  `talent29` varchar(20) NOT NULL DEFAULT '0',
  `talent30` varchar(20) NOT NULL DEFAULT '0',
  `talent31` varchar(20) NOT NULL DEFAULT '0',
  `talent32` varchar(20) NOT NULL DEFAULT '0',
  `talent33` varchar(20) NOT NULL DEFAULT '0',
  `talent34` varchar(20) NOT NULL DEFAULT '0',
  `talent35` varchar(20) NOT NULL DEFAULT '0',
  `talent36` varchar(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `Index_auid` (`auid`),
  KEY `Index_hero_id` (`hero_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;