#pragma once

/*
namespace Render
{
	enum
	{
		PRIORITY_NA = -1,
		PRIORITY_OCCLUSIONQUERY,

		PRIORITY_MESHES_OPAQUE,
		PRIORITY_MESHES_GRASS,
		PRIORITY_MESHES_TREE,
		PRIORITY_NOPOSTEFFECT_SOLID,

		PRIORITY_TERRAIN_LAYER0,
		PRIORITY_TERRAIN_LAYER1,
		PRIORITY_TERRAIN_OBJECTS,
		PRIORITY_TERRAIN_DECALS,

		PRIORITY_TRANSPARENT,
		PRIORITY_EMISSIVE,
		PRIORITY_NOPOSTEFFECT_TRANS,

    PRIORITY_DISTORTION,
    PRIORITY_HEIGHTFOG,

		PRIORITY_COUNT
	};
};
*/