#pragma once

namespace Render
{
	/// Тип элемента вершины
	enum EVertexElementType
	{
		VERTEXELEMENTTYPE_FLOAT1,
		VERTEXELEMENTTYPE_FLOAT2,
		VERTEXELEMENTTYPE_FLOAT3,
		VERTEXELEMENTTYPE_FLOAT4,
		VERTEXELEMENTTYPE_D3DCOLOR,
		VERTEXELEMENTTYPE_UBYTE4,
		VERTEXELEMENTTYPE_SHORT2,
		VERTEXELEMENTTYPE_SHORT4,
		VERTEXELEMENTTYPE_UBYTE4N,
		VERTEXELEMENTTYPE_SHORT2N,
		VERTEXELEMENTTYPE_SHORT4N,
		VERTEXELEMENTTYPE_USHORT2N,
		VERTEXELEMENTTYPE_USHORT4N,
		VERTEXELEMENTTYPE_UDEC3,
		VERTEXELEMENTTYPE_DEC3N,
		VERTEXELEMENTTYPE_FLOAT16_2,
		VERTEXELEMENTTYPE_FLOAT16_4,
		VERTEXELEMENTTYPE_UNUSED,
	};
}; // namespace Render