#pragma once

namespace Render
{
	/// Тип использования элемента вершины
	enum EVertexElementUsage
	{
		VERETEXELEMENTUSAGE_POSITION,
		VERETEXELEMENTUSAGE_BLENDWEIGHT,
		VERETEXELEMENTUSAGE_BLENDINDICES,
		VERETEXELEMENTUSAGE_NORMAL,
		VERETEXELEMENTUSAGE_PSIZE,
		VERETEXELEMENTUSAGE_TEXCOORD,
		VERETEXELEMENTUSAGE_TANGENT,
		VERETEXELEMENTUSAGE_BINORMAL,
		VERETEXELEMENTUSAGE_TESSFACTOR,
		VERETEXELEMENTUSAGE_POSITIONT,
		VERETEXELEMENTUSAGE_COLOR,
		VERETEXELEMENTUSAGE_FOG,
		VERETEXELEMENTUSAGE_DEPTH,
		VERETEXELEMENTUSAGE_SAMPLE,
	};
}; // namespace Render