#! /bin/bash
### BEGIN INIT INFO
# Provides:          pw-xs
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PW Exchange Working service
# Description:       This file should be run PrimeWorld Exchange Working services
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Oleg Malaphey <oleg.malaphey@nivalnetwork.com>

# Uncomment following line for debug mode.
#set -x

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="PW Exchange working Service."
NAME="pw-xs"
DAEMON="/bin/bash"
DAEMON_ARGS="-c"
SCRIPTNAME=/etc/init.d/$NAME

#PIDFILE=/var/run/$NAME.pid

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# check rundir and daemon. if they doesn't exists than exit with status 1
[ -d $RUNDIR ] || return 1
[ -x $DAEMON ] || return 1
[ -x $PYTHON ] || return 1

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

VERBOSE=yes

#
# Function that starts the daetatus_of_procon/service
#
do_start()
{
	# functions params
	INSTANCE=$1
	RUNSCRIPT_ARGS=$2
	LOGGING=$3
	RUN_MARKER=$4
	PIDFILE=$5

	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --background -c $USER --chdir $RUNDIR --pidfile $PIDFILE --exec $PYTHON --test -- \
		 "$PYTHON_ARGS $RUNSCRIPT $RUNSCRIPT_ARGS $LOGGING" > /dev/null \
		|| return 1
	start-stop-daemon --start --quiet --background -c $USER --chdir $RUNDIR --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- \
		$DAEMON_ARGS "exec $PYTHON $PYTHON_ARGS $RUNSCRIPT $RUNSCRIPT_ARGS $LOGGING"\
	|| return 2

	sleep {{ conf['sleep_xs'] }}
	# Check if proc was running.
	pgrep -f "$PYTHON $PYTHON_ARGS $RUNSCRIPT $RUNSCRIPT_ARGS" > /dev/null || return 2
	# Check if created "run marker".
	test -f $RUN_MARKER || return 2

	# Add code here, if necessary, that waits for the process to be ready
	# to handle requests from services started subsequently which depend
	# on this one.  As a last resort, sleep for some time.
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# functions params
	PIDFILE=$1

	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=INT/120/TERM/30/KILL/5 --user $USER --pidfile $PIDFILE
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	# Wait for children to finish too if this is a daemon that forks
	# and if the daemon is only ever run from this initscript.
	# If the above conditions are not satisfied then add some other code
	# that waits for the process to drop all resources that could be
	# needed by services started subsequently.  A last resort is to
	# sleep for some time.
	#start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --user $USER --exec $DAEMON
	#[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {

	# functions params
	PIDFILE=$1

	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
	start-stop-daemon --stop --signal 1 --quiet --user $USER --pidfile $PIDFILE --name $NAME
	return 0
}

# Check instnace name
if ! test -z $2
then
	if  ! echo ${INSTANCE[@]} | grep $2 > /dev/null
	then
		[ "$VERBOSE" != no ] && echo -n "Instance \"$2\" not found."
		[ "$VERBOSE" != no ] && log_end_msg 1
		exit 1
	fi
fi

case "$1" in
  start)
	if test -z $2
	then
		for i in ${INSTANCE[@]};
		do
			[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME ${INSTANCE[$i]}"
			do_start "${INSTANCE[$i]}" "${RUNSCRIPT_ARGS[$i]}" "${LOGGING[$i]}" "${RUN_MARKER[$i]}" "/var/run/${NAME}_${INSTANCE[$i]}.pid"
			case "$?" in
				0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
				1) [ "$VERBOSE" != no ] && (log_progress_msg "already started"; log_end_msg 255)  ;;
				2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
			esac
		done
	else
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME ${INSTANCE[$2]}"
		do_start "${INSTANCE[$2]}" "${RUNSCRIPT_ARGS[$2]}" "${LOGGING[$2]}" "${RUN_MARKER[$2]}" "/var/run/${NAME}_${INSTANCE[$2]}.pid"
		case "$?" in
				0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
				1) [ "$VERBOSE" != no ] && (log_progress_msg "already started"; log_end_msg 255)  ;;
				2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
	fi
	;;
  stop)
	if test -z $2
	then
		for i in ${INSTANCE[@]};
		do
			[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME ${INSTANCE[$i]}"
			do_stop "/var/run/${NAME}_${INSTANCE[$i]}.pid"
			case "$?" in
				0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
				1) [ "$VERBOSE" != no ] && (log_progress_msg "already stopped"; log_end_msg 255) ;;
				2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
			esac
		done
	else
		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME ${INSTANCE[$2]}"
		do_stop "/var/run/${NAME}_${INSTANCE[$2]}.pid"
		case "$?" in
			0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
			1) [ "$VERBOSE" != no ] && (log_progress_msg "already stopped"; log_end_msg 255) ;;
			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
	fi
	;;
  status)
	if test -z $2
	then
		for i in ${INSTANCE[@]};
		do
			status_of_proc "${NAME}_${INSTANCE[$i]}" "${NAME} ${INSTANCE[$i]}"
			let exitstatus+=$?
		done
		exit $exitstatus
	else
		status_of_proc "${NAME}_${INSTANCE[$2]}" "${NAME} ${INSTANCE[$2]}" && exit 0 || exit $?
	fi
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	if test -z $2
	then
		for i in ${INSTANCE[@]};
		do
			log_daemon_msg "Restarting $DESC" "$NAME ${INSTANCE[$i]}"
			do_stop "/var/run/${NAME}_${INSTANCE[$i]}.pid"
			case "$?" in
			  0|1)
				do_start "${INSTANCE[$i]}" "${RUNSCRIPT_ARGS[$i]}" "${LOGGING[$i]}" "${RUN_MARKER[$i]}" "/var/run/${NAME}_${INSTANCE[$i]}.pid"
				case "$?" in
					0) log_end_msg 0 ;;
					1) log_end_msg 1 ;; # Old process is still running
					*) log_end_msg 1 ;; # Failed to start
				esac
				;;
			  *)
			  	# Failed to stop
				log_end_msg 1
				;;
			esac
		done
	else
		log_daemon_msg "Restarting $DESC" "$NAME ${INSTANCE[$2]}"
		do_stop "/var/run/${NAME}_${INSTANCE[$2]}.pid"
		case "$?" in
		  0|1)
			do_start "${INSTANCE[$2]}" "${RUNSCRIPT_ARGS[$2]}" "${LOGGING[$2]}" "${RUN_MARKER[$2]}" "/var/run/${NAME}_${INSTANCE[$2]}.pid"
			case "$?" in
				0) log_end_msg 0 ;;
				1) log_end_msg 1 ;; # Old process is still running
				*) log_end_msg 1 ;; # Failed to start
			esac
			;;
		  *)
		  	# Failed to stop
			log_end_msg 1
			;;
		esac
	fi
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac