#ifndef SOCIALLOBBYLOG_H_INCLUDED
#define SOCIALLOBBYLOG_H_INCLUDED

//
//Shortcuts for ugly logging macroses
//

#define SOCLOBBY_SVC_CHNL "social_lobby"

#define SOCLOBBY_LOG_MSG LOG_M( SOCLOBBY_SVC_CHNL ).Trace
#define SOCLOBBY_LOG_DBG LOG_D( SOCLOBBY_SVC_CHNL ).Trace
#define SOCLOBBY_LOG_ERR LOG_E( SOCLOBBY_SVC_CHNL ).Trace
#define SOCLOBBY_LOG_WRN LOG_W( SOCLOBBY_SVC_CHNL ).Trace
#define SOCLOBBY_LOG_CRI LOG_C( SOCLOBBY_SVC_CHNL ).Trace

#endif SOCIALLOBBYLOG_H_INCLUDED
