set_alias local My

kill_unit DummyDPS
kill_unit DummyDPSAoE
wait_steps 10 
spawn_creep DummyDPS /Creeps/Spawners/Test/DummyTest_DPS744.CREEP 30 47 1
spawn_creep DummyDPSAoE /Creeps/Spawners/Test/DummyTest_DPS744.CREEP 28 45 1
teleport_to My 40 40
wait_steps 10 

refresh_cd My


//unit_stat My 0
wait_steps 10 


use_talent My Artist_A4
wait_steps 3
use_talent_unit My Artist_A1 DummyDPS 
wait_steps 15
use_talent_unit My Artist_A2 DummyDPS 
attack_unit My DummyDPS 

wait_steps 26 
use_talent_unit My Artist_A1 DummyDPS 
wait_steps 26 
use_talent_unit My Artist_A1 DummyDPS 
wait_steps 26 
use_talent_unit My Artist_A1 DummyDPS 

wait_steps 100
// goto 2  // - для бесконечного цикла, чтобы запускать процесс надолго

