set_alias local My
//use_talent My Mowgli_A1
//wait_steps 30

kill_unit DummyDPS
wait_steps 10 
spawn_creep DummyDPS /Creeps/Spawners/Test/DummyTest_DPS744.CREEP 30 47 1
teleport_to My 40 40
wait_steps 10 

refresh_cd My
wait_steps 10 


use_talent_unit My Mowgli_A4 My
wait_steps 5
use_talent_unit My Mowgli_A3 DummyDPS 
attack_unit My DummyDPS 
wait_steps 15



wait_steps 100
// goto 4  // - для бесконечного цикла, чтобы запускать процесс надолго

