// подготовка
set_alias local My
set_alias 01 Victim1
set_alias 02 Victim2
set_alias 03 Victim3


//------------------------------ раз скрипт не может по другому - тупо пытаемся купить все таланты в игре.

activate_talent My Gender_M_1
activate_talent My Gender_F_1
activate_talent My G001
activate_talent My G002
activate_talent My G003
activate_talent My G004
activate_talent My G005
activate_talent My G006
activate_talent My G007
activate_talent My G008
activate_talent My G009
activate_talent My G010
activate_talent My G011
activate_talent My G012
activate_talent My G013
activate_talent My G014
activate_talent My G015
activate_talent My G016
activate_talent My G017
activate_talent My G018
activate_talent My G019
activate_talent My G020
activate_talent My G021
activate_talent My G022
activate_talent My G023
activate_talent My G024
activate_talent My G025
activate_talent My G026
activate_talent My G027
activate_talent My G028
activate_talent My G029
activate_talent My G030
activate_talent My G031
activate_talent My G032
activate_talent My G033
activate_talent My G034
activate_talent My G035
activate_talent My G036
activate_talent My G037
activate_talent My G038
activate_talent My G039
activate_talent My G040
activate_talent My G041
activate_talent My G042
activate_talent My G043
activate_talent My G044
activate_talent My G045
activate_talent My G046
activate_talent My G047
activate_talent My G048
activate_talent My G049
activate_talent My G050
activate_talent My G051
activate_talent My G052
activate_talent My G053
activate_talent My G054
activate_talent My G055
activate_talent My G056
activate_talent My G057
activate_talent My G058
activate_talent My G059
activate_talent My G060
activate_talent My G061
activate_talent My G062
activate_talent My G063
activate_talent My G064
activate_talent My G065
activate_talent My G066
activate_talent My G067
activate_talent My G068
activate_talent My G069
activate_talent My G070
activate_talent My G071
activate_talent My G072
activate_talent My G073
activate_talent My G074
activate_talent My G075
activate_talent My G076
activate_talent My G077
activate_talent My G078
activate_talent My G079
activate_talent My G080
activate_talent My G081
activate_talent My G082
activate_talent My G083
activate_talent My G084
activate_talent My G085
activate_talent My G086
activate_talent My G087
activate_talent My G088
activate_talent My G089
activate_talent My G090
activate_talent My G091
activate_talent My G092
activate_talent My G093
activate_talent My G094
activate_talent My G095
activate_talent My G096
activate_talent My G097
activate_talent My G098
activate_talent My G099
activate_talent My G100
activate_talent My G101
activate_talent My G102
activate_talent My G103
activate_talent My G104
activate_talent My G105
activate_talent My G106
activate_talent My G107
activate_talent My G108
activate_talent My G109
activate_talent My G110
activate_talent My G111
activate_talent My G112
activate_talent My G113
activate_talent My G114
activate_talent My G115
activate_talent My G116
activate_talent My G117
activate_talent My G118
activate_talent My G119
activate_talent My G120
activate_talent My G121
activate_talent My G122
activate_talent My G123
activate_talent My G124
activate_talent My G125
activate_talent My G126
activate_talent My G127
activate_talent My G128
activate_talent My G129
activate_talent My G130
activate_talent My G131
activate_talent My G132
activate_talent My G133
activate_talent My G134
activate_talent My G135
activate_talent My G136
activate_talent My G137
activate_talent My G138
activate_talent My G139
activate_talent My G140
activate_talent My G141
activate_talent My G142
activate_talent My G143
activate_talent My G144
activate_talent My G145
activate_talent My G146
activate_talent My G147
activate_talent My G148
activate_talent My G149
activate_talent My G150
activate_talent My G151
activate_talent My G152
activate_talent My G153
activate_talent My G154
activate_talent My G155
activate_talent My G156
activate_talent My G157
activate_talent My G158
activate_talent My G159
activate_talent My G160
activate_talent My G161
activate_talent My G162
activate_talent My G163
activate_talent My G164
activate_talent My G165
activate_talent My G166
activate_talent My G167
activate_talent My G168
activate_talent My G169
activate_talent My G170
activate_talent My G171
activate_talent My G172
activate_talent My G173
activate_talent My G174
activate_talent My G175
activate_talent My G176
activate_talent My G177
activate_talent My G178
activate_talent My G179
activate_talent My G180
activate_talent My G181
activate_talent My G182
activate_talent My G183
activate_talent My G184
activate_talent My G185
activate_talent My G186
activate_talent My G187
activate_talent My G188
activate_talent My G189
activate_talent My G190
activate_talent My G191
activate_talent My G192
activate_talent My G193
activate_talent My G194
activate_talent My G195
activate_talent My G196
activate_talent My G197
activate_talent My G198
activate_talent My G199
activate_talent My G200
activate_talent My G201
activate_talent My G202
activate_talent My G203
activate_talent My G204
activate_talent My G205
activate_talent My G206
activate_talent My G207
activate_talent My G208
activate_talent My G209
activate_talent My G210
activate_talent My G211
activate_talent My G212
activate_talent My G213
activate_talent My G214
activate_talent My G215
activate_talent My G216
activate_talent My G217
activate_talent My G218
activate_talent My G219
activate_talent My G220
activate_talent My G221
activate_talent My G222
activate_talent My G223
activate_talent My G224
activate_talent My G225
activate_talent My G226
activate_talent My G227
activate_talent My G228
activate_talent My G229
activate_talent My G230
activate_talent My G231
activate_talent My G232
activate_talent My G233
activate_talent My G234
activate_talent My G235
activate_talent My G236
activate_talent My G237
activate_talent My G238
activate_talent My G239
activate_talent My G240
activate_talent My G241
activate_talent My G242
activate_talent My G243
activate_talent My G244
activate_talent My G245
activate_talent My G246
activate_talent My G247
activate_talent My G248
activate_talent My G249
activate_talent My G250
activate_talent My G251
activate_talent My G252
activate_talent My G253
activate_talent My G254
activate_talent My G255
activate_talent My G256
activate_talent My G257
activate_talent My G258
activate_talent My G259
activate_talent My G260
activate_talent My G261
activate_talent My G262
activate_talent My G263
activate_talent My G264
activate_talent My G265
activate_talent My G266
activate_talent My G267
activate_talent My G268
activate_talent My G269
activate_talent My G270
activate_talent My G271
activate_talent My G272
activate_talent My G273
activate_talent My G274
activate_talent My G275
activate_talent My G276
activate_talent My G277
activate_talent My G278
activate_talent My G279
activate_talent My G280
activate_talent My G281
activate_talent My G282
activate_talent My G283
activate_talent My G284
activate_talent My G285
activate_talent My G286
activate_talent My G287
activate_talent My G288
activate_talent My G289
activate_talent My G290
activate_talent My G291
activate_talent My G292
activate_talent My G293
activate_talent My G294
activate_talent My G295
activate_talent My G296
activate_talent My G297
activate_talent My G298
activate_talent My G299
activate_talent My G300
//add_gold My -2671700       //чтобы забрать весь тот лишний прайм, что нам дал чит - не работает



//------------------------------ набираем стеки стекающихся талантов
//unit_stat My 12 10 //делаем огромную регенерацию маны

teleport_to My 40 40
teleport_to Victim1 43 43
teleport_to Victim2 37 37
teleport_to Victim3 37 43
unit_stat Victim1 0 1
unit_stat Victim2 0 1
unit_stat Victim3 0 1

wait_steps 50 
resurrect_hero Victim1 
resurrect_hero Victim2 
resurrect_hero Victim3 
wait_steps 10
teleport_to Victim1 43 43
teleport_to Victim2 37 37
teleport_to Victim3 37 43
wait_steps 50 
resurrect_hero Victim1 
resurrect_hero Victim2 
resurrect_hero Victim3 
wait_steps 10
teleport_to Victim1 43 43
teleport_to Victim2 37 37
teleport_to Victim3 37 43
wait_steps 50 
resurrect_hero Victim1 
resurrect_hero Victim2 
resurrect_hero Victim3 
wait_steps 10
teleport_to Victim1 43 43
teleport_to Victim2 37 37
teleport_to Victim3 37 43


spawn_creep DummyBurst /Creeps/Spawners/Test/DummyTest_Burst744.CREEP 30 30 1
spawn_creep DummyDPS /Creeps/Spawners/Test/DummyTest_DPS744.CREEP 40 30 1
spawn_creep DummyBurstAoE /Creeps/Spawners/Test/DummyTest_Burst744.CREEP 28 28 1
spawn_creep DummyDPSAoE /Creeps/Spawners/Test/DummyTest_DPS744.CREEP 38 28 1

unit_stat My 12 10

echo "Конец скрипта подготовки!"


