/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace StatisticCore.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class GMEditFieldInfo : TBase
  {
    private long _auid;
    private string _gmlogin;
    private int _timestamp;
    private string _field;
    private string _oldvalue;
    private string _newvalue;

    public long Auid
    {
      get
      {
        return _auid;
      }
      set
      {
        __isset.auid = true;
        this._auid = value;
      }
    }

    public string Gmlogin
    {
      get
      {
        return _gmlogin;
      }
      set
      {
        __isset.gmlogin = true;
        this._gmlogin = value;
      }
    }

    public int Timestamp
    {
      get
      {
        return _timestamp;
      }
      set
      {
        __isset.timestamp = true;
        this._timestamp = value;
      }
    }

    public string Field
    {
      get
      {
        return _field;
      }
      set
      {
        __isset.field = true;
        this._field = value;
      }
    }

    public string Oldvalue
    {
      get
      {
        return _oldvalue;
      }
      set
      {
        __isset.oldvalue = true;
        this._oldvalue = value;
      }
    }

    public string Newvalue
    {
      get
      {
        return _newvalue;
      }
      set
      {
        __isset.newvalue = true;
        this._newvalue = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool auid;
      public bool gmlogin;
      public bool timestamp;
      public bool field;
      public bool oldvalue;
      public bool newvalue;
    }

    public GMEditFieldInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              Auid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Gmlogin = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              Timestamp = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Field = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Oldvalue = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              Newvalue = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("GMEditFieldInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.auid) {
        field.Name = "auid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Auid);
        oprot.WriteFieldEnd();
      }
      if (Gmlogin != null && __isset.gmlogin) {
        field.Name = "gmlogin";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Gmlogin);
        oprot.WriteFieldEnd();
      }
      if (__isset.timestamp) {
        field.Name = "timestamp";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Timestamp);
        oprot.WriteFieldEnd();
      }
      if (Field != null && __isset.field) {
        field.Name = "field";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Field);
        oprot.WriteFieldEnd();
      }
      if (Oldvalue != null && __isset.oldvalue) {
        field.Name = "oldvalue";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Oldvalue);
        oprot.WriteFieldEnd();
      }
      if (Newvalue != null && __isset.newvalue) {
        field.Name = "newvalue";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Newvalue);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("GMEditFieldInfo(");
      sb.Append("Auid: ");
      sb.Append(Auid);
      sb.Append(",Gmlogin: ");
      sb.Append(Gmlogin);
      sb.Append(",Timestamp: ");
      sb.Append(Timestamp);
      sb.Append(",Field: ");
      sb.Append(Field);
      sb.Append(",Oldvalue: ");
      sb.Append(Oldvalue);
      sb.Append(",Newvalue: ");
      sb.Append(Newvalue);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
