/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace StatisticCore.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SocialRegisterInfo : TBase
  {
    private string _hostid;
    private string _auid;
    private string _snid;
    private string _snuid;
    private string _muid;

    public string Hostid
    {
      get
      {
        return _hostid;
      }
      set
      {
        __isset.hostid = true;
        this._hostid = value;
      }
    }

    public string Auid
    {
      get
      {
        return _auid;
      }
      set
      {
        __isset.auid = true;
        this._auid = value;
      }
    }

    public string Snid
    {
      get
      {
        return _snid;
      }
      set
      {
        __isset.snid = true;
        this._snid = value;
      }
    }

    public string Snuid
    {
      get
      {
        return _snuid;
      }
      set
      {
        __isset.snuid = true;
        this._snuid = value;
      }
    }

    public string Muid
    {
      get
      {
        return _muid;
      }
      set
      {
        __isset.muid = true;
        this._muid = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool hostid;
      public bool auid;
      public bool snid;
      public bool snuid;
      public bool muid;
    }

    public SocialRegisterInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Hostid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Auid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Snid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Snuid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Muid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SocialRegisterInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Hostid != null && __isset.hostid) {
        field.Name = "hostid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Hostid);
        oprot.WriteFieldEnd();
      }
      if (Auid != null && __isset.auid) {
        field.Name = "auid";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Auid);
        oprot.WriteFieldEnd();
      }
      if (Snid != null && __isset.snid) {
        field.Name = "snid";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Snid);
        oprot.WriteFieldEnd();
      }
      if (Snuid != null && __isset.snuid) {
        field.Name = "snuid";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Snuid);
        oprot.WriteFieldEnd();
      }
      if (Muid != null && __isset.muid) {
        field.Name = "muid";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Muid);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SocialRegisterInfo(");
      sb.Append("Hostid: ");
      sb.Append(Hostid);
      sb.Append(",Auid: ");
      sb.Append(Auid);
      sb.Append(",Snid: ");
      sb.Append(Snid);
      sb.Append(",Snuid: ");
      sb.Append(Snuid);
      sb.Append(",Muid: ");
      sb.Append(Muid);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
