/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Example_CONSTANTS_H
#define Example_CONSTANTS_H

#include "Example_types.h"

namespace Test {

class ExampleConstants {
 public:
  ExampleConstants();

};

extern const ExampleConstants g_Example_constants;

} // namespace

#endif
