// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Monitoring.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::Monitoring::Thrift;

class MonitoringHandler : virtual public MonitoringIf {
 public:
  MonitoringHandler() {
    // Your initialization goes here
  }

  void GetPerfCounters(std::vector<PerfCounterInfo> & _return) {
    // Your implementation goes here
    printf("GetPerfCounters\n");
  }

  int32_t RegisterPerfCounters(const std::vector<PerfCounterInfo> & counters) {
    // Your implementation goes here
    printf("RegisterPerfCounters\n");
  }

  int32_t UnregisterPerfCounters(const std::vector<std::string> & counters) {
    // Your implementation goes here
    printf("UnregisterPerfCounters\n");
  }

  int32_t UnregisterAllPerfCounters() {
    // Your implementation goes here
    printf("UnregisterAllPerfCounters\n");
  }

  void GetRegisteredPerfCounters(std::vector<PerfCounterInfo> & _return) {
    // Your implementation goes here
    printf("GetRegisteredPerfCounters\n");
  }

  void GetPerfCounterSamples(std::vector<PerfCounterSample> & _return) {
    // Your implementation goes here
    printf("GetPerfCounterSamples\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MonitoringHandler> handler(new MonitoringHandler());
  shared_ptr<TProcessor> processor(new MonitoringProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

