/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class GameSessionShortInfo : TBase
  {
    private long _sessionid;
    private List<AccountShortInfo> _teamdocts;
    private List<AccountShortInfo> _teamadorni;
    private RequestResult _result;

    public long Sessionid
    {
      get
      {
        return _sessionid;
      }
      set
      {
        __isset.sessionid = true;
        this._sessionid = value;
      }
    }

    public List<AccountShortInfo> Teamdocts
    {
      get
      {
        return _teamdocts;
      }
      set
      {
        __isset.teamdocts = true;
        this._teamdocts = value;
      }
    }

    public List<AccountShortInfo> Teamadorni
    {
      get
      {
        return _teamadorni;
      }
      set
      {
        __isset.teamadorni = true;
        this._teamadorni = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="RequestResult"/>
    /// </summary>
    public RequestResult Result
    {
      get
      {
        return _result;
      }
      set
      {
        __isset.result = true;
        this._result = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool sessionid;
      public bool teamdocts;
      public bool teamadorni;
      public bool result;
    }

    public GameSessionShortInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              Sessionid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Teamdocts = new List<AccountShortInfo>();
                TList _list22 = iprot.ReadListBegin();
                for( int _i23 = 0; _i23 < _list22.Count; ++_i23)
                {
                  AccountShortInfo _elem24 = new AccountShortInfo();
                  _elem24 = new AccountShortInfo();
                  _elem24.Read(iprot);
                  Teamdocts.Add(_elem24);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Teamadorni = new List<AccountShortInfo>();
                TList _list25 = iprot.ReadListBegin();
                for( int _i26 = 0; _i26 < _list25.Count; ++_i26)
                {
                  AccountShortInfo _elem27 = new AccountShortInfo();
                  _elem27 = new AccountShortInfo();
                  _elem27.Read(iprot);
                  Teamadorni.Add(_elem27);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              Result = (RequestResult)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("GameSessionShortInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.sessionid) {
        field.Name = "sessionid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Sessionid);
        oprot.WriteFieldEnd();
      }
      if (Teamdocts != null && __isset.teamdocts) {
        field.Name = "teamdocts";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Teamdocts.Count));
          foreach (AccountShortInfo _iter28 in Teamdocts)
          {
            _iter28.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Teamadorni != null && __isset.teamadorni) {
        field.Name = "teamadorni";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Teamadorni.Count));
          foreach (AccountShortInfo _iter29 in Teamadorni)
          {
            _iter29.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.result) {
        field.Name = "result";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Result);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("GameSessionShortInfo(");
      sb.Append("Sessionid: ");
      sb.Append(Sessionid);
      sb.Append(",Teamdocts: ");
      sb.Append(Teamdocts);
      sb.Append(",Teamadorni: ");
      sb.Append(Teamadorni);
      sb.Append(",Result: ");
      sb.Append(Result);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
