/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class HeroPricesResponse : TBase
  {
    private RequestResult _result;
    private List<HeroPriceEvent> _heroEvents;
    private List<HeroPrice> _defaultPrices;

    /// <summary>
    /// 
    /// <seealso cref="RequestResult"/>
    /// </summary>
    public RequestResult Result
    {
      get
      {
        return _result;
      }
      set
      {
        __isset.result = true;
        this._result = value;
      }
    }

    public List<HeroPriceEvent> HeroEvents
    {
      get
      {
        return _heroEvents;
      }
      set
      {
        __isset.heroEvents = true;
        this._heroEvents = value;
      }
    }

    public List<HeroPrice> DefaultPrices
    {
      get
      {
        return _defaultPrices;
      }
      set
      {
        __isset.defaultPrices = true;
        this._defaultPrices = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool result;
      public bool heroEvents;
      public bool defaultPrices;
    }

    public HeroPricesResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Result = (RequestResult)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                HeroEvents = new List<HeroPriceEvent>();
                TList _list206 = iprot.ReadListBegin();
                for( int _i207 = 0; _i207 < _list206.Count; ++_i207)
                {
                  HeroPriceEvent _elem208 = new HeroPriceEvent();
                  _elem208 = new HeroPriceEvent();
                  _elem208.Read(iprot);
                  HeroEvents.Add(_elem208);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                DefaultPrices = new List<HeroPrice>();
                TList _list209 = iprot.ReadListBegin();
                for( int _i210 = 0; _i210 < _list209.Count; ++_i210)
                {
                  HeroPrice _elem211 = new HeroPrice();
                  _elem211 = new HeroPrice();
                  _elem211.Read(iprot);
                  DefaultPrices.Add(_elem211);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("HeroPricesResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.result) {
        field.Name = "result";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Result);
        oprot.WriteFieldEnd();
      }
      if (HeroEvents != null && __isset.heroEvents) {
        field.Name = "heroEvents";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, HeroEvents.Count));
          foreach (HeroPriceEvent _iter212 in HeroEvents)
          {
            _iter212.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (DefaultPrices != null && __isset.defaultPrices) {
        field.Name = "defaultPrices";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, DefaultPrices.Count));
          foreach (HeroPrice _iter213 in DefaultPrices)
          {
            _iter213.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("HeroPricesResponse(");
      sb.Append("Result: ");
      sb.Append(Result);
      sb.Append(",HeroEvents: ");
      sb.Append(HeroEvents);
      sb.Append(",DefaultPrices: ");
      sb.Append(DefaultPrices);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
