/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class QuestForTalentInfo : TBase
  {
    private int _questId;
    private int _startTime;
    private int _endTime;
    private int _talentAwardPersistentId;
    private string _talentAwardName;
    private int _shardsSpent;
    private string _fullDynamicQuestInfo;
    private int _currentObjectiveValue;
    private string _currentObjectiveData;
    private int _currentObjectiveId;
    private int _currentAwardId;
    private string _totalObjectiveData;
    private int _reason;

    public int QuestId
    {
      get
      {
        return _questId;
      }
      set
      {
        __isset.questId = true;
        this._questId = value;
      }
    }

    public int StartTime
    {
      get
      {
        return _startTime;
      }
      set
      {
        __isset.startTime = true;
        this._startTime = value;
      }
    }

    public int EndTime
    {
      get
      {
        return _endTime;
      }
      set
      {
        __isset.endTime = true;
        this._endTime = value;
      }
    }

    public int TalentAwardPersistentId
    {
      get
      {
        return _talentAwardPersistentId;
      }
      set
      {
        __isset.talentAwardPersistentId = true;
        this._talentAwardPersistentId = value;
      }
    }

    public string TalentAwardName
    {
      get
      {
        return _talentAwardName;
      }
      set
      {
        __isset.talentAwardName = true;
        this._talentAwardName = value;
      }
    }

    public int ShardsSpent
    {
      get
      {
        return _shardsSpent;
      }
      set
      {
        __isset.shardsSpent = true;
        this._shardsSpent = value;
      }
    }

    public string FullDynamicQuestInfo
    {
      get
      {
        return _fullDynamicQuestInfo;
      }
      set
      {
        __isset.fullDynamicQuestInfo = true;
        this._fullDynamicQuestInfo = value;
      }
    }

    public int CurrentObjectiveValue
    {
      get
      {
        return _currentObjectiveValue;
      }
      set
      {
        __isset.currentObjectiveValue = true;
        this._currentObjectiveValue = value;
      }
    }

    public string CurrentObjectiveData
    {
      get
      {
        return _currentObjectiveData;
      }
      set
      {
        __isset.currentObjectiveData = true;
        this._currentObjectiveData = value;
      }
    }

    public int CurrentObjectiveId
    {
      get
      {
        return _currentObjectiveId;
      }
      set
      {
        __isset.currentObjectiveId = true;
        this._currentObjectiveId = value;
      }
    }

    public int CurrentAwardId
    {
      get
      {
        return _currentAwardId;
      }
      set
      {
        __isset.currentAwardId = true;
        this._currentAwardId = value;
      }
    }

    public string TotalObjectiveData
    {
      get
      {
        return _totalObjectiveData;
      }
      set
      {
        __isset.totalObjectiveData = true;
        this._totalObjectiveData = value;
      }
    }

    public int Reason
    {
      get
      {
        return _reason;
      }
      set
      {
        __isset.reason = true;
        this._reason = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool questId;
      public bool startTime;
      public bool endTime;
      public bool talentAwardPersistentId;
      public bool talentAwardName;
      public bool shardsSpent;
      public bool fullDynamicQuestInfo;
      public bool currentObjectiveValue;
      public bool currentObjectiveData;
      public bool currentObjectiveId;
      public bool currentAwardId;
      public bool totalObjectiveData;
      public bool reason;
    }

    public QuestForTalentInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              QuestId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              StartTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              EndTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              TalentAwardPersistentId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              TalentAwardName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              ShardsSpent = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.String) {
              FullDynamicQuestInfo = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I32) {
              CurrentObjectiveValue = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.String) {
              CurrentObjectiveData = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              CurrentObjectiveId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.I32) {
              CurrentAwardId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.String) {
              TotalObjectiveData = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 13:
            if (field.Type == TType.I32) {
              Reason = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("QuestForTalentInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.questId) {
        field.Name = "questId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(QuestId);
        oprot.WriteFieldEnd();
      }
      if (__isset.startTime) {
        field.Name = "startTime";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(StartTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.endTime) {
        field.Name = "endTime";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(EndTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.talentAwardPersistentId) {
        field.Name = "talentAwardPersistentId";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TalentAwardPersistentId);
        oprot.WriteFieldEnd();
      }
      if (TalentAwardName != null && __isset.talentAwardName) {
        field.Name = "talentAwardName";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(TalentAwardName);
        oprot.WriteFieldEnd();
      }
      if (__isset.shardsSpent) {
        field.Name = "shardsSpent";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ShardsSpent);
        oprot.WriteFieldEnd();
      }
      if (FullDynamicQuestInfo != null && __isset.fullDynamicQuestInfo) {
        field.Name = "fullDynamicQuestInfo";
        field.Type = TType.String;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(FullDynamicQuestInfo);
        oprot.WriteFieldEnd();
      }
      if (__isset.currentObjectiveValue) {
        field.Name = "currentObjectiveValue";
        field.Type = TType.I32;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CurrentObjectiveValue);
        oprot.WriteFieldEnd();
      }
      if (CurrentObjectiveData != null && __isset.currentObjectiveData) {
        field.Name = "currentObjectiveData";
        field.Type = TType.String;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CurrentObjectiveData);
        oprot.WriteFieldEnd();
      }
      if (__isset.currentObjectiveId) {
        field.Name = "currentObjectiveId";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CurrentObjectiveId);
        oprot.WriteFieldEnd();
      }
      if (__isset.currentAwardId) {
        field.Name = "currentAwardId";
        field.Type = TType.I32;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CurrentAwardId);
        oprot.WriteFieldEnd();
      }
      if (TotalObjectiveData != null && __isset.totalObjectiveData) {
        field.Name = "totalObjectiveData";
        field.Type = TType.String;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(TotalObjectiveData);
        oprot.WriteFieldEnd();
      }
      if (__isset.reason) {
        field.Name = "reason";
        field.Type = TType.I32;
        field.ID = 13;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Reason);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("QuestForTalentInfo(");
      sb.Append("QuestId: ");
      sb.Append(QuestId);
      sb.Append(",StartTime: ");
      sb.Append(StartTime);
      sb.Append(",EndTime: ");
      sb.Append(EndTime);
      sb.Append(",TalentAwardPersistentId: ");
      sb.Append(TalentAwardPersistentId);
      sb.Append(",TalentAwardName: ");
      sb.Append(TalentAwardName);
      sb.Append(",ShardsSpent: ");
      sb.Append(ShardsSpent);
      sb.Append(",FullDynamicQuestInfo: ");
      sb.Append(FullDynamicQuestInfo);
      sb.Append(",CurrentObjectiveValue: ");
      sb.Append(CurrentObjectiveValue);
      sb.Append(",CurrentObjectiveData: ");
      sb.Append(CurrentObjectiveData);
      sb.Append(",CurrentObjectiveId: ");
      sb.Append(CurrentObjectiveId);
      sb.Append(",CurrentAwardId: ");
      sb.Append(CurrentAwardId);
      sb.Append(",TotalObjectiveData: ");
      sb.Append(TotalObjectiveData);
      sb.Append(",Reason: ");
      sb.Append(Reason);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
