/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RerollShopGroupPriceByIdResponse : TBase
  {
    private RequestResult _result;
    private RerollShopGroupPriceEvent _groupEvent;
    private List<RerollShopGroupPrice> _defaultPrices;

    /// <summary>
    /// 
    /// <seealso cref="RequestResult"/>
    /// </summary>
    public RequestResult Result
    {
      get
      {
        return _result;
      }
      set
      {
        __isset.result = true;
        this._result = value;
      }
    }

    public RerollShopGroupPriceEvent GroupEvent
    {
      get
      {
        return _groupEvent;
      }
      set
      {
        __isset.groupEvent = true;
        this._groupEvent = value;
      }
    }

    public List<RerollShopGroupPrice> DefaultPrices
    {
      get
      {
        return _defaultPrices;
      }
      set
      {
        __isset.defaultPrices = true;
        this._defaultPrices = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool result;
      public bool groupEvent;
      public bool defaultPrices;
    }

    public RerollShopGroupPriceByIdResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Result = (RequestResult)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              GroupEvent = new RerollShopGroupPriceEvent();
              GroupEvent.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                DefaultPrices = new List<RerollShopGroupPrice>();
                TList _list242 = iprot.ReadListBegin();
                for( int _i243 = 0; _i243 < _list242.Count; ++_i243)
                {
                  RerollShopGroupPrice _elem244 = new RerollShopGroupPrice();
                  _elem244 = new RerollShopGroupPrice();
                  _elem244.Read(iprot);
                  DefaultPrices.Add(_elem244);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RerollShopGroupPriceByIdResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.result) {
        field.Name = "result";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Result);
        oprot.WriteFieldEnd();
      }
      if (GroupEvent != null && __isset.groupEvent) {
        field.Name = "groupEvent";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        GroupEvent.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (DefaultPrices != null && __isset.defaultPrices) {
        field.Name = "defaultPrices";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, DefaultPrices.Count));
          foreach (RerollShopGroupPrice _iter245 in DefaultPrices)
          {
            _iter245.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RerollShopGroupPriceByIdResponse(");
      sb.Append("Result: ");
      sb.Append(Result);
      sb.Append(",GroupEvent: ");
      sb.Append(GroupEvent== null ? "<null>" : GroupEvent.ToString());
      sb.Append(",DefaultPrices: ");
      sb.Append(DefaultPrices);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
