/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RerollShopGroupCurrenciesResponse : TBase
  {
    private RequestResult _result;
    private List<RerollShopGroupCurrenciesEvent> _groupEvents;
    private List<RerollShopGroupCurrencies> _defaultCurrencies;

    /// <summary>
    /// 
    /// <seealso cref="RequestResult"/>
    /// </summary>
    public RequestResult Result
    {
      get
      {
        return _result;
      }
      set
      {
        __isset.result = true;
        this._result = value;
      }
    }

    public List<RerollShopGroupCurrenciesEvent> GroupEvents
    {
      get
      {
        return _groupEvents;
      }
      set
      {
        __isset.groupEvents = true;
        this._groupEvents = value;
      }
    }

    public List<RerollShopGroupCurrencies> DefaultCurrencies
    {
      get
      {
        return _defaultCurrencies;
      }
      set
      {
        __isset.defaultCurrencies = true;
        this._defaultCurrencies = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool result;
      public bool groupEvents;
      public bool defaultCurrencies;
    }

    public RerollShopGroupCurrenciesResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Result = (RequestResult)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                GroupEvents = new List<RerollShopGroupCurrenciesEvent>();
                TList _list262 = iprot.ReadListBegin();
                for( int _i263 = 0; _i263 < _list262.Count; ++_i263)
                {
                  RerollShopGroupCurrenciesEvent _elem264 = new RerollShopGroupCurrenciesEvent();
                  _elem264 = new RerollShopGroupCurrenciesEvent();
                  _elem264.Read(iprot);
                  GroupEvents.Add(_elem264);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                DefaultCurrencies = new List<RerollShopGroupCurrencies>();
                TList _list265 = iprot.ReadListBegin();
                for( int _i266 = 0; _i266 < _list265.Count; ++_i266)
                {
                  RerollShopGroupCurrencies _elem267 = new RerollShopGroupCurrencies();
                  _elem267 = new RerollShopGroupCurrencies();
                  _elem267.Read(iprot);
                  DefaultCurrencies.Add(_elem267);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RerollShopGroupCurrenciesResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.result) {
        field.Name = "result";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Result);
        oprot.WriteFieldEnd();
      }
      if (GroupEvents != null && __isset.groupEvents) {
        field.Name = "groupEvents";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, GroupEvents.Count));
          foreach (RerollShopGroupCurrenciesEvent _iter268 in GroupEvents)
          {
            _iter268.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (DefaultCurrencies != null && __isset.defaultCurrencies) {
        field.Name = "defaultCurrencies";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, DefaultCurrencies.Count));
          foreach (RerollShopGroupCurrencies _iter269 in DefaultCurrencies)
          {
            _iter269.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RerollShopGroupCurrenciesResponse(");
      sb.Append("Result: ");
      sb.Append(Result);
      sb.Append(",GroupEvents: ");
      sb.Append(GroupEvents);
      sb.Append(",DefaultCurrencies: ");
      sb.Append(DefaultCurrencies);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
