/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TournamentGamesInfo : TBase
  {
    private long _GameStartTime;
    private int _GameDuration;
    private string _SessionId;

    public long GameStartTime
    {
      get
      {
        return _GameStartTime;
      }
      set
      {
        __isset.GameStartTime = true;
        this._GameStartTime = value;
      }
    }

    public int GameDuration
    {
      get
      {
        return _GameDuration;
      }
      set
      {
        __isset.GameDuration = true;
        this._GameDuration = value;
      }
    }

    public string SessionId
    {
      get
      {
        return _SessionId;
      }
      set
      {
        __isset.SessionId = true;
        this._SessionId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool GameStartTime;
      public bool GameDuration;
      public bool SessionId;
    }

    public TournamentGamesInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              GameStartTime = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              GameDuration = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              SessionId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TournamentGamesInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.GameStartTime) {
        field.Name = "GameStartTime";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(GameStartTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.GameDuration) {
        field.Name = "GameDuration";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(GameDuration);
        oprot.WriteFieldEnd();
      }
      if (SessionId != null && __isset.SessionId) {
        field.Name = "SessionId";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(SessionId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TournamentGamesInfo(");
      sb.Append("GameStartTime: ");
      sb.Append(GameStartTime);
      sb.Append(",GameDuration: ");
      sb.Append(GameDuration);
      sb.Append(",SessionId: ");
      sb.Append(SessionId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
