/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TradeEventModel : TBase
  {
    private int _persistentId;
    private int _startTime;
    private int _endTime;
    private string _locale;
    private bool _enabled;
    private string _description;
    private string _title;
    private string _text;
    private string _completionTalentId;
    private int _completionTalentRatio;
    private string _experienceCurrencyName;
    private string _bannerUrl;
    private List<TradeEventGroupModel> _tradeEventGroups;
    private List<WorldRatingRewardRelation> _worldRatingRewardRelations;
    private List<ExperienceRewardRelation> _experienceRewardRelations;
    private string _rewardsBlockTitle;
    private int _guid;

    public int PersistentId
    {
      get
      {
        return _persistentId;
      }
      set
      {
        __isset.persistentId = true;
        this._persistentId = value;
      }
    }

    public int StartTime
    {
      get
      {
        return _startTime;
      }
      set
      {
        __isset.startTime = true;
        this._startTime = value;
      }
    }

    public int EndTime
    {
      get
      {
        return _endTime;
      }
      set
      {
        __isset.endTime = true;
        this._endTime = value;
      }
    }

    public string Locale
    {
      get
      {
        return _locale;
      }
      set
      {
        __isset.locale = true;
        this._locale = value;
      }
    }

    public bool Enabled
    {
      get
      {
        return _enabled;
      }
      set
      {
        __isset.enabled = true;
        this._enabled = value;
      }
    }

    public string Description
    {
      get
      {
        return _description;
      }
      set
      {
        __isset.description = true;
        this._description = value;
      }
    }

    public string Title
    {
      get
      {
        return _title;
      }
      set
      {
        __isset.title = true;
        this._title = value;
      }
    }

    public string Text
    {
      get
      {
        return _text;
      }
      set
      {
        __isset.text = true;
        this._text = value;
      }
    }

    public string CompletionTalentId
    {
      get
      {
        return _completionTalentId;
      }
      set
      {
        __isset.completionTalentId = true;
        this._completionTalentId = value;
      }
    }

    public int CompletionTalentRatio
    {
      get
      {
        return _completionTalentRatio;
      }
      set
      {
        __isset.completionTalentRatio = true;
        this._completionTalentRatio = value;
      }
    }

    public string ExperienceCurrencyName
    {
      get
      {
        return _experienceCurrencyName;
      }
      set
      {
        __isset.experienceCurrencyName = true;
        this._experienceCurrencyName = value;
      }
    }

    public string BannerUrl
    {
      get
      {
        return _bannerUrl;
      }
      set
      {
        __isset.bannerUrl = true;
        this._bannerUrl = value;
      }
    }

    public List<TradeEventGroupModel> TradeEventGroups
    {
      get
      {
        return _tradeEventGroups;
      }
      set
      {
        __isset.tradeEventGroups = true;
        this._tradeEventGroups = value;
      }
    }

    public List<WorldRatingRewardRelation> WorldRatingRewardRelations
    {
      get
      {
        return _worldRatingRewardRelations;
      }
      set
      {
        __isset.worldRatingRewardRelations = true;
        this._worldRatingRewardRelations = value;
      }
    }

    public List<ExperienceRewardRelation> ExperienceRewardRelations
    {
      get
      {
        return _experienceRewardRelations;
      }
      set
      {
        __isset.experienceRewardRelations = true;
        this._experienceRewardRelations = value;
      }
    }

    public string RewardsBlockTitle
    {
      get
      {
        return _rewardsBlockTitle;
      }
      set
      {
        __isset.rewardsBlockTitle = true;
        this._rewardsBlockTitle = value;
      }
    }

    public int Guid
    {
      get
      {
        return _guid;
      }
      set
      {
        __isset.guid = true;
        this._guid = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool persistentId;
      public bool startTime;
      public bool endTime;
      public bool locale;
      public bool enabled;
      public bool description;
      public bool title;
      public bool text;
      public bool completionTalentId;
      public bool completionTalentRatio;
      public bool experienceCurrencyName;
      public bool bannerUrl;
      public bool tradeEventGroups;
      public bool worldRatingRewardRelations;
      public bool experienceRewardRelations;
      public bool rewardsBlockTitle;
      public bool guid;
    }

    public TradeEventModel() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              PersistentId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              StartTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              EndTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Locale = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Bool) {
              Enabled = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              Description = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.String) {
              Title = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.String) {
              Text = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.String) {
              CompletionTalentId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              CompletionTalentRatio = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.String) {
              ExperienceCurrencyName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.String) {
              BannerUrl = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 13:
            if (field.Type == TType.List) {
              {
                TradeEventGroups = new List<TradeEventGroupModel>();
                TList _list430 = iprot.ReadListBegin();
                for( int _i431 = 0; _i431 < _list430.Count; ++_i431)
                {
                  TradeEventGroupModel _elem432 = new TradeEventGroupModel();
                  _elem432 = new TradeEventGroupModel();
                  _elem432.Read(iprot);
                  TradeEventGroups.Add(_elem432);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 14:
            if (field.Type == TType.List) {
              {
                WorldRatingRewardRelations = new List<WorldRatingRewardRelation>();
                TList _list433 = iprot.ReadListBegin();
                for( int _i434 = 0; _i434 < _list433.Count; ++_i434)
                {
                  WorldRatingRewardRelation _elem435 = new WorldRatingRewardRelation();
                  _elem435 = new WorldRatingRewardRelation();
                  _elem435.Read(iprot);
                  WorldRatingRewardRelations.Add(_elem435);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 15:
            if (field.Type == TType.List) {
              {
                ExperienceRewardRelations = new List<ExperienceRewardRelation>();
                TList _list436 = iprot.ReadListBegin();
                for( int _i437 = 0; _i437 < _list436.Count; ++_i437)
                {
                  ExperienceRewardRelation _elem438 = new ExperienceRewardRelation();
                  _elem438 = new ExperienceRewardRelation();
                  _elem438.Read(iprot);
                  ExperienceRewardRelations.Add(_elem438);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 16:
            if (field.Type == TType.String) {
              RewardsBlockTitle = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 17:
            if (field.Type == TType.I32) {
              Guid = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TradeEventModel");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.persistentId) {
        field.Name = "persistentId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(PersistentId);
        oprot.WriteFieldEnd();
      }
      if (__isset.startTime) {
        field.Name = "startTime";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(StartTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.endTime) {
        field.Name = "endTime";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(EndTime);
        oprot.WriteFieldEnd();
      }
      if (Locale != null && __isset.locale) {
        field.Name = "locale";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Locale);
        oprot.WriteFieldEnd();
      }
      if (__isset.enabled) {
        field.Name = "enabled";
        field.Type = TType.Bool;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Enabled);
        oprot.WriteFieldEnd();
      }
      if (Description != null && __isset.description) {
        field.Name = "description";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Description);
        oprot.WriteFieldEnd();
      }
      if (Title != null && __isset.title) {
        field.Name = "title";
        field.Type = TType.String;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Title);
        oprot.WriteFieldEnd();
      }
      if (Text != null && __isset.text) {
        field.Name = "text";
        field.Type = TType.String;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Text);
        oprot.WriteFieldEnd();
      }
      if (CompletionTalentId != null && __isset.completionTalentId) {
        field.Name = "completionTalentId";
        field.Type = TType.String;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CompletionTalentId);
        oprot.WriteFieldEnd();
      }
      if (__isset.completionTalentRatio) {
        field.Name = "completionTalentRatio";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CompletionTalentRatio);
        oprot.WriteFieldEnd();
      }
      if (ExperienceCurrencyName != null && __isset.experienceCurrencyName) {
        field.Name = "experienceCurrencyName";
        field.Type = TType.String;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ExperienceCurrencyName);
        oprot.WriteFieldEnd();
      }
      if (BannerUrl != null && __isset.bannerUrl) {
        field.Name = "bannerUrl";
        field.Type = TType.String;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(BannerUrl);
        oprot.WriteFieldEnd();
      }
      if (TradeEventGroups != null && __isset.tradeEventGroups) {
        field.Name = "tradeEventGroups";
        field.Type = TType.List;
        field.ID = 13;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, TradeEventGroups.Count));
          foreach (TradeEventGroupModel _iter439 in TradeEventGroups)
          {
            _iter439.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (WorldRatingRewardRelations != null && __isset.worldRatingRewardRelations) {
        field.Name = "worldRatingRewardRelations";
        field.Type = TType.List;
        field.ID = 14;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, WorldRatingRewardRelations.Count));
          foreach (WorldRatingRewardRelation _iter440 in WorldRatingRewardRelations)
          {
            _iter440.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (ExperienceRewardRelations != null && __isset.experienceRewardRelations) {
        field.Name = "experienceRewardRelations";
        field.Type = TType.List;
        field.ID = 15;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ExperienceRewardRelations.Count));
          foreach (ExperienceRewardRelation _iter441 in ExperienceRewardRelations)
          {
            _iter441.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (RewardsBlockTitle != null && __isset.rewardsBlockTitle) {
        field.Name = "rewardsBlockTitle";
        field.Type = TType.String;
        field.ID = 16;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(RewardsBlockTitle);
        oprot.WriteFieldEnd();
      }
      if (__isset.guid) {
        field.Name = "guid";
        field.Type = TType.I32;
        field.ID = 17;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Guid);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TradeEventModel(");
      sb.Append("PersistentId: ");
      sb.Append(PersistentId);
      sb.Append(",StartTime: ");
      sb.Append(StartTime);
      sb.Append(",EndTime: ");
      sb.Append(EndTime);
      sb.Append(",Locale: ");
      sb.Append(Locale);
      sb.Append(",Enabled: ");
      sb.Append(Enabled);
      sb.Append(",Description: ");
      sb.Append(Description);
      sb.Append(",Title: ");
      sb.Append(Title);
      sb.Append(",Text: ");
      sb.Append(Text);
      sb.Append(",CompletionTalentId: ");
      sb.Append(CompletionTalentId);
      sb.Append(",CompletionTalentRatio: ");
      sb.Append(CompletionTalentRatio);
      sb.Append(",ExperienceCurrencyName: ");
      sb.Append(ExperienceCurrencyName);
      sb.Append(",BannerUrl: ");
      sb.Append(BannerUrl);
      sb.Append(",TradeEventGroups: ");
      sb.Append(TradeEventGroups);
      sb.Append(",WorldRatingRewardRelations: ");
      sb.Append(WorldRatingRewardRelations);
      sb.Append(",ExperienceRewardRelations: ");
      sb.Append(ExperienceRewardRelations);
      sb.Append(",RewardsBlockTitle: ");
      sb.Append(RewardsBlockTitle);
      sb.Append(",Guid: ");
      sb.Append(Guid);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
