/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace AccountLib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UserDumpsDataResponse : TBase
  {
    private List<string> _avaialbleBackups;
    private RequestResult _result;

    public List<string> AvaialbleBackups
    {
      get
      {
        return _avaialbleBackups;
      }
      set
      {
        __isset.avaialbleBackups = true;
        this._avaialbleBackups = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="RequestResult"/>
    /// </summary>
    public RequestResult Result
    {
      get
      {
        return _result;
      }
      set
      {
        __isset.result = true;
        this._result = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool avaialbleBackups;
      public bool result;
    }

    public UserDumpsDataResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                AvaialbleBackups = new List<string>();
                TList _list358 = iprot.ReadListBegin();
                for( int _i359 = 0; _i359 < _list358.Count; ++_i359)
                {
                  string _elem360 = null;
                  _elem360 = iprot.ReadString();
                  AvaialbleBackups.Add(_elem360);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Result = (RequestResult)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("UserDumpsDataResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AvaialbleBackups != null && __isset.avaialbleBackups) {
        field.Name = "avaialbleBackups";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, AvaialbleBackups.Count));
          foreach (string _iter361 in AvaialbleBackups)
          {
            oprot.WriteString(_iter361);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.result) {
        field.Name = "result";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Result);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("UserDumpsDataResponse(");
      sb.Append("AvaialbleBackups: ");
      sb.Append(AvaialbleBackups);
      sb.Append(",Result: ");
      sb.Append(Result);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
