
USER_ALREADY_LOGGEDIN = 1
SESSION_ALREADY_CLOSED = 2
CONTEXT_CHECK_FAIL = 3
SESSION_NOT_FOUND = 4
PROJECT_NOT_FOUND = 5
PROJECT_NOT_ALLOWED = 6
MESSAGE_BAD_FORMAT = 7
UNSUPPORTED_METHOD = 8
PARAM_INVALID = 9