DO $$
BEGIN

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ro') THEN
    CREATE ROLE ro;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'producer') THEN
    CREATE ROLE producer LOGIN PASSWORD '#PRODUCER_PWD#' IN ROLE ro;
  END IF;

END $$;

CREATE DATABASE #ANALYSISDB_NAME#
  WITH OWNER = dbadmin
       ENCODING = 'UTF8'
       CONNECTION LIMIT = -1;
GRANT CONNECT, TEMPORARY ON DATABASE #ANALYSISDB_NAME# TO ro;