DO $$
BEGIN

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ro') THEN
    CREATE ROLE ro;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rw') THEN
    CREATE ROLE rw;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'logging') THEN
    CREATE ROLE logging LOGIN PASSWORD '#LOGGING_PWD#' IN ROLE rw;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'reporting') THEN
    CREATE ROLE reporting LOGIN PASSWORD '#REPORTING_PWD#' IN ROLE ro;
  END IF;

END $$;

CREATE DATABASE #LOGSDB_NAME#
  WITH OWNER = dbadminlogs
       ENCODING = 'UTF8'
       CONNECTION LIMIT = -1;
GRANT CONNECT, TEMPORARY ON DATABASE #LOGSDB_NAME# TO ro;
GRANT CONNECT, TEMPORARY ON DATABASE #LOGSDB_NAME# TO rw;
