# -*- coding: utf-8 -*-
# Automatically generated file. do not modify it!!!

class StatisticEventType:
    SESSION_FINISH = 0
    SESSION_RESOURCE = 1
    SESSION_TALENT = 2
    BATH_START = 3
    BATH_FINISH = 4
    PRODUCTION_START = 5
    PRODUCTION_FINISH = 6
    TALENT_START = 7
    TALENT_FINISH = 8
    TALENT_UNSOULBOUND = 9
    TALENT_SOULBOUND = 10
    TALENT_UPGRADE = 11
    TALENTS_REMOVE = 12
    FREE_SKIP = 13
    DAILY_COMPLETE = 14
    PRODUCTION_SKIP = 15
    HERO_LEVEL = 16
    HERO_RATING = 17
    HERO_FORCE = 18
    BUILDING_LEVEL = 19
    TALENT_REFORGE = 20
    GUILD_SESSION_RESOURCE = 21
    BUILDING_BOOST = 22
    RED_PERL_BUY = 23
    TALENT_REFORGE_UPGRADE = 24

