@echo launching x_coordinator...
@start /MIN xs_Coordinator.bat
@echo waiting 1 second...
@call python delay.py 1.0
@echo launching x_servers...
@start /MIN xs_8811.bat
@start /MIN xs_8812.bat
@call nginx_reload.bat
